const express = require('express'); 
const router = express.Router(); 
const ClientController = require('../controllers/ClientController'); 
const ReviewController = require('../controllers/ReviewController');
const { isAuth } = require('../middlewares/auth');
router.get('/', ClientController.home); 
router.get('/tours', ClientController.tourList);
router.get('/tours/:slug', ClientController.tourDetail);
router.post('/reviews', isAuth, ReviewController.create);
module.exports = router;